### ISSUE TITLE
Failed at start script

### ISSUE THREAD

**Issue by Notsalgia** [ZeroDiscord/EconomyBot#10]
I converted this into a repl. I changed all of the things in BotConfig.js and I ran `npm install`.
I got this error:
`
/home/runner/EconomyBot/index.js:4
client.eco = new Eco.Manager(); // quick.eco
             ^

TypeError: Eco.Manager is not a constructor
    at Object.<anonymous> (/home/runner/EconomyBot/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EconomyBot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EconomyBot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-23T20_58_13_650Z-debug.log`

pls help

I also tried node index.js and got this error:
 node index.js
/home/runner/EconomyBot/index.js:4
client.eco = new Eco.Manager(); // quick.eco
             ^

TypeError: Eco.Manager is not a constructor
    at Object.<anonymous> (/home/runner/EconomyBot/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by ZeroDiscord** [comment]
Hello there!
I'd like you to do the following steps:
- [ ]  `npm install`
- [ ] `npm rebuild` [ If there are any build time errors ]
- [ ] `node .`
