### ISSUE TITLE
Error with token

### ISSUE THREAD

**Issue by Apelsin4k** [ZeroDiscord/EconomyBot#23]
Hello, i get error when i run command node . in Visual Studio Code. I download this project, entered valid token, and run npm install, but I still get this error.

```
[WS => Manager] Manager was destroyed. Called by:
Error: MANAGER_DESTROYED
    at WebSocketManager.destroy (C:\FluffyBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:333:54)
    at Client.destroy (C:\FluffyBot\node_modules\discord.js\src\client\Client.js:237:13)
    at Client.login (C:\FluffyBot\node_modules\discord.js\src\client\Client.js:226:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4020) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\FluffyBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\FluffyBot\node_modules\discord.js\src\client\Client.js:223:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ZeroDiscord** [comment]
Assisted on discord
